# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renameMat.ui'
#
# Created by: PySide2 UI code generator (modified from PyQt5)
#
# WARNING: Any manual changes made to this file will be lost when pyside2-uic is
# run again.  Do not edit this file unless you know what you are doing.
#
# MODIFIED: Changed from PyQt5 to PySide2 for Maya 2022 compatibility

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(892, 652)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list_wgt = QtWidgets.QTableWidget(Dialog)
        self.list_wgt.setShowGrid(True)
        self.list_wgt.setWordWrap(True)
        self.list_wgt.setCornerButtonEnabled(True)
        self.list_wgt.setRowCount(0)
        self.list_wgt.setColumnCount(5)
        self.list_wgt.setObjectName("list_wgt")
        item = QtWidgets.QTableWidgetItem()
        self.list_wgt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_wgt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_wgt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_wgt.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_wgt.setHorizontalHeaderItem(4, item)
        self.horizontalLayout.addWidget(self.list_wgt)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.list_wgt.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "mesh"))
        item = self.list_wgt.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "shadingGrps"))
        item = self.list_wgt.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "shader_name"))
        item = self.list_wgt.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "new_shader_name"))
